{{- if .Values.imagePullSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eva-vision.fullname" . }}-regcred
  labels:
    {{- include "eva-vision.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s.dkr.ecr.%s.amazonaws.com\":{\"username\":\"AWS\",\"password\":\"%s\",\"email\":\"none\",\"auth\":\"%s\"}}}" .Values.imagePullSecrets.account .Values.imagePullSecrets.region .Values.imagePullSecrets.password (printf "AWS:%s" .Values.imagePullSecrets.password | b64enc) | b64enc }}
{{- end }}
