apiVersion: v1
kind: Service
metadata:
  name: {{ include "eva-vision.fullname" . }}
  labels:
    {{- include "eva-vision.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      port: {{ .Values.service.port }}
      targetPort: proxy
      protocol: TCP
      name: http-proxy
  selector:
    {{- include "eva-vision.selectorLabels" . | nindent 4 }}
